# ---------------------- #
# site config            #
# ---------------------- #
name: sinosub
baseurl:
url: https://www.sinosub.,com
keywords: sinosub
description: .

# ---------------------- #
# jekyll                 #
# ---------------------- #
safe: true
auto: true
rouge: true
markdown: kramdown
timezone: America/Los_Angeles

# ---------------------- #
# deployment             #
# ---------------------- #
deploy:
repository:
branch:

theme: jekyll-theme-cayman